---
#
#
#

    - name: install postgresql packages
      apt: name={{item}} state=latest install_recommends=yes update_cache=yes
      become: yes
      with_items:
        - postgresql
        - postgresql-contrib

    - name: install postgresql server development packages
      apt: name={{item}} state=latest install_recommends=yes update_cache=yes
      become: yes
      with_items:
        - postgresql-server-dev-all
