---
#
#  Installing on Ubuntu
#

- name: ensure required packages are installed for Java 8
  apt: name="{{item}}" state=latest update_cache=yes
  become: yes
  with_items:
    - python-software-properties
    - software-properties-common

- name: Add webupd8team/java repository
  apt_repository: repo="ppa:webupd8team/java" update_cache=yes
  become: yes

- name: Autoaccept license for Java
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  become: yes

#- name: Accept Java 8 License
#  become: yes
#  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Update APT package cache
  apt: update_cache=yes
  become: yes

- name: Install Java 8 and set Env
  apt: name={{item}} state=latest install_recommends=yes update_cache=yes
  become: yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
