# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "box-cutter/ubuntu1604"
  config.vm.box = "bento/ubuntu-16.04"

  # имя в `vagrant global-status`
  config.vm.define "vg-ubuntu1604x64-1" do |t|
  end
  # custom name in VirtualBox
  config.vm.provider "virtualbox" do |vb|
     vb.name = "vg-ubuntu1604x64-1"
  end

  config.vm.hostname = "VG-UBUNTU1604-x64-1"

  #config.vm.network "public_network"
  config.vm.network "public_network", ip: "192.168.1.235"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"


  # selenium node port
  # config.vm.network :forwarded_port, guest: 5556, host: 5556

  # Apahe www ports
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 81, host: 8081
  config.vm.network :forwarded_port, guest: 82, host: 8082

  # Postgres port
  # config.vm.network :forwarded_port, guest: 5556, host: 5556



  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
#     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.customize ["modifyvm", :id, "--memory", "512"]
#     vb.customize ["modifyvm", :id, "--memory", "1024"]
#     vb.customize ["modifyvm", :id, "--memory", "1536"]
#     vb.customize ["modifyvm", :id, "--memory", "2048"]
#     vb.customize ["modifyvm", :id, "--memory", "3072"]
#     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--vram", "128"]
#     vb.customize ["modifyvm", :id, "--vram", "256"]
     vb.customize ["modifyvm", :id, "--cpus", 1]
#     vb.customize ["modifyvm", :id, "--cpus", 2]
#     vb.customize ["modifyvm", :id, "--cpus", 4]
     vb.customize ["modifyvm", :id, "--ioapic", "on"]
     vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
#     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
#     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    sudo apt-get update
#    sudo apt-get install -y ansible sshpass
#  SHELL

#  config.vm.provision :ansible do |ansible|
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
